export interface Template {
  id: string;
  name: string;
  price: string;
  priceCents: number;
  description: string;
  hook: string;
  builtFor: string;
  features: string[];
  tier: "free" | "paid";
}

export const TEMPLATES: Template[] = [
  {
    id: "productivity-agent",
    name: "Productivity Agent",
    price: "Free",
    priceCents: 0,
    description: "Morning report, evening check-in, Telegram assistant",
    hook: "Morning report ready when you wake up.",
    builtFor: "Founders",
    features: [
      "Morning report at 07:00",
      "Evening check-in at 21:00",
      "Telegram interactive commands",
    ],
    tier: "free",
  },
  {
    id: "inbox-agent",
    name: "Inbox Agent",
    price: "$19",
    priceCents: 1900,
    description: "Email categorization, summarization, and digest",
    hook: "3 urgent, 5 action needed, 12 FYI, 8 newsletter.",
    builtFor: "Everyone",
    features: [
      "Auto-scan every 2 hours",
      "Categorize: urgent / action / FYI / newsletter",
      "Telegram digest with approval",
    ],
    tier: "paid",
  },
  {
    id: "reddit-hn-digest",
    name: "Reddit & HN Digest",
    price: "$19",
    priceCents: 1900,
    description: "Daily curated digest from Reddit and Hacker News",
    hook: "Never miss what matters on Reddit and HN.",
    builtFor: "Developers",
    features: [
      "Subreddit + HN monitoring",
      "Learns your preferences over time",
      "Morning digest to Telegram",
    ],
    tier: "paid",
  },
  {
    id: "youtube-digest",
    name: "YouTube Digest",
    price: "$19",
    priceCents: 1900,
    description: "Morning summary of new videos from favorite channels",
    hook: "Your YouTube feed, distilled to what matters.",
    builtFor: "Everyone",
    features: [
      "Channel monitoring",
      "Key takeaway extraction",
      "Morning briefing to Telegram",
    ],
    tier: "paid",
  },
  {
    id: "health-tracker",
    name: "Health Tracker",
    price: "$29",
    priceCents: 2900,
    description: "Food and symptom tracking with weekly correlation analysis",
    hook: "Discover what foods affect how you feel.",
    builtFor: "Health-conscious",
    features: [
      "3x daily check-ins via Telegram",
      "Food-symptom correlation analysis",
      "Weekly health report",
    ],
    tier: "paid",
  },
  {
    id: "earnings-tracker",
    name: "Earnings Tracker",
    price: "$29",
    priceCents: 2900,
    description: "Tech/AI earnings reports with beat/miss analysis",
    hook: "Stay on top of earnings season effortlessly.",
    builtFor: "Investors",
    features: [
      "Weekly upcoming earnings preview",
      "Real-time result alerts",
      "Beat/miss analysis",
    ],
    tier: "paid",
  },
  {
    id: "research-agent",
    name: "Research Agent",
    price: "$39",
    priceCents: 3900,
    description: "Multi-source scan, daily digest, trend detection",
    hook: "Know when competitors change anything — in 5 minutes.",
    builtFor: "Product Teams",
    features: [
      "Scan X, HN, Reddit, RSS",
      "AI-filtered daily digest",
      "Weekly trend summary",
    ],
    tier: "paid",
  },
  {
    id: "knowledge-base",
    name: "Knowledge Base",
    price: "$39",
    priceCents: 3900,
    description: "Personal knowledge management from URLs, articles, tweets",
    hook: "Your second brain for everything you read.",
    builtFor: "Researchers",
    features: [
      "Save and tag articles, tweets, videos",
      "Natural language search",
      "Auto-categorization",
    ],
    tier: "paid",
  },
  {
    id: "family-calendar",
    name: "Family Calendar",
    price: "$39",
    priceCents: 3900,
    description: "Household coordination with calendar aggregation",
    hook: "Everyone in sync, nothing forgotten.",
    builtFor: "Families",
    features: [
      "Calendar aggregation across family",
      "Morning briefing + evening prep",
      "Grocery inventory management",
    ],
    tier: "paid",
  },
  {
    id: "content-agent",
    name: "Content Agent",
    price: "$49",
    priceCents: 4900,
    description: "Research, draft in your voice, post with approval, analyze",
    hook: "Your X account grows while you sleep.",
    builtFor: "Creators",
    features: [
      "Trending topic research",
      "Draft in your voice (style guide)",
      "Post with Telegram approval",
      "24h engagement analysis",
    ],
    tier: "paid",
  },
  {
    id: "personal-crm",
    name: "Personal CRM",
    price: "$49",
    priceCents: 4900,
    description: "Contact management with auto-discovery from email",
    hook: "Never lose touch with anyone important.",
    builtFor: "Networkers",
    features: [
      "Auto-discover contacts from email + calendar",
      "Meeting briefings",
      "Follow-up tracking",
    ],
    tier: "paid",
  },
  {
    id: "youtube-creator",
    name: "YouTube Creator",
    price: "$69",
    priceCents: 6900,
    description: "Content pipeline for YouTube creators",
    hook: "From idea to upload, fully assisted.",
    builtFor: "YouTubers",
    features: [
      "Breaking news scouting in your niche",
      "Differentiated video idea pitches",
      "Full outlines with hooks and thumbnails",
    ],
    tier: "paid",
  },
  {
    id: "devops-agent",
    name: "DevOps Agent",
    price: "$79",
    priceCents: 7900,
    description: "Infrastructure monitoring and self-healing",
    hook: "Sleep through incidents, wake up to fixes.",
    builtFor: "Engineers",
    features: [
      "Health checks every 15 minutes",
      "Auto-restart failed services",
      "Security audit + backup verification",
    ],
    tier: "paid",
  },
  {
    id: "customer-service",
    name: "Customer Service",
    price: "$79",
    priceCents: 7900,
    description: "Multi-channel customer support with knowledge base",
    hook: "24/7 support without the headcount.",
    builtFor: "Businesses",
    features: [
      "Gmail inquiry monitoring",
      "Intent classification + KB-backed replies",
      "Approval required before every reply",
    ],
    tier: "paid",
  },
  {
    id: "sales-agent",
    name: "Sales Agent",
    price: "$79",
    priceCents: 7900,
    description: "Lead finding, outreach drafts, CRM sync, follow-up",
    hook: "Find leads overnight, inbox full by morning.",
    builtFor: "Sales Teams",
    features: [
      "Buying signal detection",
      "Lead scoring (1-10)",
      "Personalized outreach drafts",
      "Auto follow-up at 3 days",
    ],
    tier: "paid",
  },
  {
    id: "six-agent-company",
    name: "6-Agent Company",
    price: "$149",
    priceCents: 14900,
    description: "6 coordinated agents with standup, memory, and self-correction",
    hook: "6 AI agents running your company for $8/month.",
    builtFor: "AI Enthusiasts",
    features: [
      "Coordinator, Executor, Observer, Analyst, Content, Growth",
      "Morning standup meetings",
      "Ralph Wiggum self-correction loop",
      "5-type memory system",
    ],
    tier: "paid",
  },
];
